<a href="https://colab.research.google.com/github/zzzer0-wav/myDTA_2026/blob/main/homework/python_numpy_practice_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 Практика: Python + NumPy для аналітика даних

Цей блокнот — чиста практика. Мінімум теорії, максимум задач.

---
### Як працювати
- **Shift+Enter** — запустити клітинку
- Спочатку спробуй сам, потім порівняй з розв'язком у блокноті з відповідями
- Навіть неправильна спроба вчить більше ніж підгляд
---

---
# Частина 1 — Основний синтаксис Python

## Блок 1.1 — Змінні та типи даних

### 📋 Задача 1
Є дані одного продажу. Створи змінні та виведи підсумок у такому форматі:
```
Товар:     Ноутбук
Ціна:      34500 грн
Знижка:    10%
До сплати: 31050.0 грн
```

In [ ]:
product  = 'Ноутбук'
price    = 34500
discount = 10   # відсотків
# Порахуй суму до сплати та виведи результат

print(f"Товар: {product} \n"
      f"Ціна: {price} грн.\n"
      f"Знижка: {discount} % \n"
      f"До сплати: {round(price - (price * discount/100),2)} грн.")

Товар: Ноутбук 
Ціна: 34500 грн.
Знижка: 10 % 
До сплати: 31050.0 грн.


### 📋 Задача 2
Визнач тип кожної змінної та виведи його.
Потім перетвори рядок `'2024'` на ціле число та додай 1.

In [ ]:
a = 42
b = 3.14
c = 'аналітик'
d = True
e = '2024'

# Виведи тип кожної змінної — hint: type()
# Перетвори e на int та додай 1
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(int(e))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'str'>
2024


---
## Блок 1.2 — Рядки та форматування

### 📋 Задача 3
Маємо сирий рядок із назвою міста та пробілами. Зроби:
1. Прибери зайві пробіли по краях — `.strip()`
2. Зроби першу літеру великою — `.title()`
3. Виведи кількість символів в очищеній назві
4. Перевір чи починається рядок з літери `'К'`

In [ ]:
city = '   харків   '
print(f'{city.strip()}'
      f'\n{city.strip().title()}'
      f'\n{len(city.strip())}'
      f'\nПочинається з літери К: {city.strip().startswith('K')}')

харків
Харків
6
Починається з літери К: False


### 📋 Задача 4
Є рядок з даними у форматі CSV (через кому).
Розбий його на окремі значення і виведи кожне з його номером.
```
0: Олена
1: Маркетинг
2: 32000
...
```

In [ ]:
row = 'Олена,Маркетинг,32000,Київ,5'

# Розбий рядок на список — hint: .split(',')
# Виведи кожне значення з індексом — hint: enumerate()

split = row.split(',')
for i, values in enumerate(split):
    print(f'{i}: {values}')

0: Олена
1: Маркетинг
2: 32000
3: Київ
4: 5


---
## Блок 1.3 — Списки

### 📋 Задача 5
Маємо список оцінок студента. Виконай дії:
1. Додай оцінку `91` в кінець — `.append()`
2. Видали `47` (помилка введення) — `.remove()`
3. Відсортуй за спаданням — `.sort(reverse=True)`
4. Виведи найвищу та найнижчу оцінку

In [ ]:
grades = [85, 47, 92, 78, 88, 74, 95, 61]
grades.append(91)
print(grades)

grades.remove(47)
print(grades)

grades.sort(reverse=True)
print(grades)
print(f'Найвища: {max(grades)}')
print(f'Найнижча: {min(grades)}')


[85, 47, 92, 78, 88, 74, 95, 61, 91]
[85, 92, 78, 88, 74, 95, 61, 91]
[95, 92, 91, 88, 85, 78, 74, 61]
Найвища: 95
Найнижча: 61


### 📋 Задача 6
Є список чисел. За допомогою **зрізів** виконай без циклів:
1. Перші 3 елементи
2. Останні 3 елементи
3. Кожен другий елемент
4. Список у зворотному порядку

In [ ]:
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(numbers[:3])
print(numbers[-3:])
print(numbers[1::2])
print(numbers[::-1])

[10, 20, 30]
[80, 90, 100]
[20, 40, 60, 80, 100]
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]


### 📋 Задача 7 — List comprehension
Перепиши кожну операцію **одним рядком** за допомогою list comprehension:
`[вираз for елемент in список]`

In [ ]:
prices = [100, 250, 80, 420, 175, 310]

# 1. Список цін з ПДВ (×1.2) — одним рядком
prices_vat = [el * 1.2 for el in prices]
print(prices_vat)

# 2. Тільки ціни більше 200 — одним рядком
big_prices = [el for el in prices if el > 200]
print(big_prices)

# 3. Рядки виду 'Ціна: 100 грн' для кожної ціни — одним рядком
labels = [f'Ціна: {el}' for el in prices]
print(labels)


[120.0, 300.0, 96.0, 504.0, 210.0, 372.0]
[250, 420, 310]
['Ціна: 100', 'Ціна: 250', 'Ціна: 80', 'Ціна: 420', 'Ціна: 175', 'Ціна: 310']


---
## Блок 1.4 — Словники

### 📋 Задача 8
Є словник із даними співробітника. Виконай:
1. Додай ключ `'досвід'` зі значенням `5`
2. Збільш зарплату на 10%
3. Виведи всі ключі, значення та пари `key: value`
4. Перевір чи є ключ `'відділ'`

In [ ]:
employee = {
    "ім'я":    'Максим',
    'відділ':  'IT',
    'зарплата': 65000,
    'місто':   'Харків'
}

employee['experience'] = 5
employee['зарплата'] *= 1.1

for key, value in employee.items():
    print(key, ':', value)

if 'відділ' in employee:
   print(f'\nЗнайдено: {employee['відділ']}!')
else:
   print(f'\nНезнайдено!')


ім'я : Максим
відділ : IT
зарплата : 71500.0
місто : Харків
experience : 5

Знайдено: IT!



### 📋 Задача 9
Є список рядків-записів. Перетвори їх у список словників:
```python
[{'місто': 'Київ', 'продажі': 145000, 'місяць': 'Січень'}, ...]
```
Підказка: `split(',')` та `int()`

In [ ]:
raw_data = [
    'Київ,145000,Січень',
    'Харків,98000,Січень',
    'Одеса,76000,Січень',
    'Львів,112000,Січень',
]

records = []
# Твій код — заповни records
for row in raw_data:
    parts = row.split(',')
    records.append({
        'місто': parts[0],
        'продажі': int(parts[1]),
        'місяць': parts[2]
    })
print(records)

[{'місто': 'Київ', 'продажі': 145000, 'місяць': 'Січень'}, {'місто': 'Харків', 'продажі': 98000, 'місяць': 'Січень'}, {'місто': 'Одеса', 'продажі': 76000, 'місяць': 'Січень'}, {'місто': 'Львів', 'продажі': 112000, 'місяць': 'Січень'}]


---
## Блок 1.5 — Умови та цикли

### 📋 Задача 10
Напиши функцію `classify_sale(amount)`, яка повертає:
- `'Мале'` — менше 500 грн
- `'Середнє'` — від 500 до 2000 грн включно
- `'Велике'` — більше 2000 грн

Протестуй на значеннях: `150, 750, 500, 2000, 5500`

In [ ]:
def classify_sale(amount):
    pass   # заміни pass на свій код

test_values = [150, 750, 500, 2000, 5500]
for val in test_values:
    print(f'{val:>6} грн → {classify_sale(val)}')


   150 грн → None
   750 грн → None
   500 грн → None
  2000 грн → None
  5500 грн → None


### 📋 Задача 11
Є список чисел із «брудними» значеннями (від'ємні — помилки, нулі — відсутні дані).

Напиши цикл `for`, який:
1. Пропускає від'ємні числа — `continue`
2. Зупиняється на нулі — `break`
3. Рахує суму та кількість валідних значень
4. Виводить середнє

In [ ]:
measurements = [23, 45, -5, 67, 12, -3, 89, 0, 44, 56]

total = 0
count = 0

for val in measurements:
    if val < 0:
        continue
    if val == 0:
        break
    total += val
    count += 1
print(f'Сума: {total}')
print(f'Кількість валідних значень: {count}')
print(f'Середнє: {total / count}')


Сума: 236
Кількість валідних значень: 5
Середнє: 47.2


---
## Блок 1.6 — Функції

### 📋 Задача 12
Напиши функцію `summary(data)`, яка приймає список чисел і повертає **словник**:
`{'min': ..., 'max': ..., 'sum': ..., 'mean': ..., 'count': ...}`

Використовуй лише вбудовані функції: `min()`, `max()`, `sum()`, `len()`

In [ ]:
def summary(data):
    return {
        'min':min(data),
        'max':max(data),
        'sum':sum(data),
        'mean': sum(data) / len(data),
        'count': len(data)
    }

sales = [4500, 8200, 3100, 9700, 5600, 2300, 7800]
result = summary(sales)
print(result)


{'min': 2300, 'max': 9700, 'sum': 41200, 'mean': 5885.714285714285, 'count': 7}


### 📋 Задача 13
Напиши функцію `filter_records(records, field, value)`, яка повертає
список словників де `record[field] == value`.

Протестуй: знайди всіх з IT та всіх з Києва.

In [ ]:
employees = [
    {"ім'я": 'Олена', 'відділ': 'IT',        'місто': 'Київ'},
    {"ім'я": 'Максим', 'відділ': 'Маркетинг', 'місто': 'Харків'},
    {"ім'я": 'Аня',    'відділ': 'IT',        'місто': 'Київ'},
    {"ім'я": 'Богдан', 'відділ': 'HR',        'місто': 'Львів'},
    {"ім'я": 'Катя',   'відділ': 'IT',        'місто': 'Одеса'},
]

def filter_records(records, field, value):
    return [record for record in records if record[field] == value]

it_team = filter_records(employees, 'відділ', 'IT')
print(f'IT: {len(it_team)} осіб')

kyiv = filter_records(employees, 'місто', 'Київ')
print(f'Київ: {len(kyiv)} осіб')


IT: 3 осіб
Київ: 2 осіб


---
# Частина 2 — NumPy: масиви та операції

In [ ]:
import numpy as np
print('NumPy:', np.__version__, '✅')

NumPy: 2.0.2 ✅


---
## Блок 2.1 — Створення масивів

### 📋 Задача 14
Створи масиви різними способами і виведи для кожного: вміст, `dtype` та `shape`.

In [ ]:
# 1. Масив із списку: [5, 10, 15, 20, 25]
# 2. Масив нулів розміром 4×3
# 3. Масив одиниць розміром 2×5
# 4. Числа від 1 до 20 з кроком 3   — hint: np.arange
# 5. 6 рівномірних чисел від 0 до 1 — hint: np.linspace

five = np.array([5, 10, 15, 20, 25])
zeros = np.zeros((4, 3))
ones = np.ones((2, 5))
arange = np.arange(1, 21, 3)
linspace = np.linspace(0, 1, 6)


### 📋 Задача 15
Створи матрицю 3×3 із числами від 1 до 9, потім:
1. Виведи форму та кількість елементів
2. Змін форму на 9×1
3. Змін форму на 1×9
4. Розгорни у плоский масив — `flatten()`

In [ ]:
# Hint: np.arange(1, 10).reshape(3, 3)
print(np.arange(1, 10).reshape(3, 3))
print(np.arange(1, 10).reshape(9, 1))
print(np.arange(1, 10).reshape(1, 9))
print(np.arange(1, 10).flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


### 📋 Задача 14+ (додаткова)
Створи такі спеціальні масиви та виведи кожен:
1. Одиничну матрицю 4×4 — `np.eye()`
2. Масив із 5 випадкових цілих чисел від 1 до 100 — `np.random.randint()`
3. Масив із 4 випадкових чисел нормального розподілу (μ=0, σ=1) — `np.random.randn()`
4. Масив, заповнений числом `7`, розміром 3×3 — `np.full()`

In [ ]:
np.random.seed(42)   # фіксує випадковість — результат завжди однаковий
print(np.eye(4, 4))
print()
print(np.random.randint(1, 100, size=5))
print()
print(np.random.randn(4))
print()
print(np.full((3, 3), 7))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[52 93 15 72 61]

[-1.19780643  2.14165843 -0.094621   -0.9288281 ]

[[7 7 7]
 [7 7 7]
 [7 7 7]]


---
## Блок 2.2 — Індексація та зрізи

### 📋 Задача 16
Є масив продажів за 10 днів. Виконай вибірку **без циклів** через зрізи:
1. Перші 3 дні
2. Останні 3 дні
3. Кожен другий день
4. Дні з 3-го по 7-й включно
5. Масив у зворотному порядку

In [ ]:
daily_sales = np.array([320, 410, 285, 590, 340, 615, 280, 475, 390, 510])
print(daily_sales[:3])
print(daily_sales[-3:])
print(daily_sales[1::2])
print(daily_sales[3:8])
print(daily_sales[::-1])


[320 410 285]
[475 390 510]
[410 590 615 475 510]
[590 340 615 280 475]
[510 390 475 280 615 340 590 285 410 320]


### 📋 Задача 17
Є матриця 4×4 — продажі по магазинах (рядки) і тижнях (стовпці). Виконай вибірку:
1. Весь перший рядок (магазин 1)
2. Весь другий стовпець (тиждень 2)
3. Підматриця: магазини 2–3, тижні 2–3
4. Останній рядок і останній стовпець

In [ ]:
sales = np.array([
    [150, 210, 180, 240],   # Магазин 1
    [120, 190, 210, 175],   # Магазин 2
    [200, 165, 195, 220],   # Магазин 3
    [135, 145, 160, 195],   # Магазин 4
])
print(sales[0])
print(sales[:, 1])
print(sales[1:3, 1:3])
print(sales[-1, -1])

[150 210 180 240]
[210 190 165 145]
[[190 210]
 [165 195]]
195


### 📋 Задача 16+ (додаткова)
Є масив з 10 елементів. Виконай:
1. Виведи елементи з парними індексами (0, 2, 4...)
2. Виведи три середніх елементи (індекси 3, 4, 5)
3. Змін значення останніх двох елементів на `0`
4. Виведи масив після зміни

In [ ]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])
print(arr[0::2])
print(arr[3:6])
arr[-2:] = 0
print(arr)

[11 33 55 77 99]
[44 55 66]
[11 22 33 44 55 66 77 88  0  0]


---
## Блок 2.3 — Математичні операції та векторизація

### 📋 Задача 18
Є масив цін у доларах. Виконай **без циклів**:
1. Переведи в гривні (курс 41)
2. Додай ПДВ 20%
3. Заокругли до цілих
4. Знайди мінімум, максимум, суму, середнє

In [ ]:
prices_usd = np.array([12.5, 34.0, 8.75, 59.99, 23.0, 41.5])
prices_uah = prices_usd * 41
prices_uah_pdv20 = prices_uah * 1.2
prices_uah_pdv20
print(prices_uah)
# print(np.round(prices_uah_pdv20))
print(prices_uah_pdv20.astype(int))
print(f'min: {prices_uah_pdv20}')

[ 512.5  1394.    358.75 2459.59  943.   1701.5 ]
[ 615 1672  430 2951 1131 2041]
min: [ 615.    1672.8    430.5   2951.508 1131.6   2041.8  ]


### 📋 Задача 19
Є два масиви — кількість і ціна за одиницю. Знайди:
1. Виручку по кожному товару (поелементне множення)
2. Загальну виручку
3. Середню ціну товарів
4. Товар з максимальною виручкою — `np.argmax()`

In [ ]:
quantities = np.array([30, 12, 85, 7,  42, 19])
unit_price = np.array([500, 2400, 120, 8500, 350, 1200])
names      = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор', 'Мишка', 'Навушники']
total = quantities * unit_price
print(f'Виручка по кожному товару: {total}')
print(f'Заральна виручка: {total.sum()} грн')
print(f'Середня ціна товарів: {np.round(total.mean(), 2)} грн')
print(f'ID товару з максимальною виручою: {np.argmax(total)}')

Виручка по кожному товару: [15000 28800 10200 59500 14700 22800]
Заральна виручка: 151000 грн
Середня ціна товарів: 25166.67 грн
ID товару з максимальною виручою: 3


### 📋 Задача 18+ (додаткова)
Є масив балів тесту (0–100). Знайди **без циклів**:
1. Кількість студентів, що склали тест (бал >= 60)
2. Кількість студентів, що не склали
3. Відсоток тих, хто склав
4. Середній бал серед тих, хто склав

In [ ]:
scores = np.array([72, 45, 88, 91, 55, 63, 78, 34, 82, 67,
                   59, 94, 41, 76, 85, 52, 69, 38, 73, 90])
passed = scores >= 60
not_passed = scores < 60
pct_passed = passed.sum() / len(scores) * 100

print(f'Учнів здало тест: {passed.sum()}')
print(f'Учнів що не здали: {not_passed.sum()}')
print(f'% тих, хто склав: {pct_passed}%')
print(f'Середній бал тих, хто склав: {scores[passed].mean().astype(int)}')

Учнів здало тест: 13
Учнів що не здали: 7
% тих, хто склав: 65.0%
Середній бал тих, хто склав: 79


---
## Блок 2.4 — Булева індексація та фільтрація

### 📋 Задача 20
Є масив температур за місяць. Знайди:
1. Дні з температурою вище 25°C
2. Кількість таких днів
3. Середня температура в «спекотні» (>25°C) і «прохолодні» (≤25°C) дні
4. Заміни всі від'ємні значення нулем

In [ ]:
temps = np.array([22, 28, 31, 19, 25, 34, 27, 18, -2, 23,
                  29, 33, 21, 26, 30, 17, 24, 32, 28, 20,
                  -1, 25, 31, 29, 23, 27, 35, 22, 19, 26])

hot_days = temps > 25
cold_days = temps <= 25

print(f'Теплі дні: {np.where(hot_days)[0] + 1}')
print(f'Кількість теплих днів: {hot_days.sum()}')
print(f'Середня спекотних: {temps[hot_days].mean():.1f}')
print(f'Середня прохолодних: {temps[cold_days].mean():.1f}')

temps[temps < 0] = 0
print(f'Після заміни: {temps}')

Теплі дні: [ 2  3  6  7 11 12 14 15 18 19 23 24 26 27 30]
Кількість теплих днів: 15
Середня спекотних: 29.7
Середня прохолодних: 18.3
Після заміни: [22 28 31 19 25 34 27 18  0 23 29 33 21 26 30 17 24 32 28 20  0 25 31 29
 23 27 35 22 19 26]


### 📋 Задача 21
Є дані про замовлення: масив сум та масив статусів. Виконай аналіз:
1. Сума всіх завершених замовлень (`'done'`)
2. Кількість `'pending'`
3. Середня сума скасованих (`'cancelled'`)
4. Завершені замовлення з сумою > 1000 грн

In [ ]:
np.random.seed(42)
amounts  = np.random.randint(200, 5000, 20)
statuses = np.random.choice(['done', 'pending', 'cancelled'], 20,
                             p=[0.6, 0.25, 0.15])

done_mask = statuses == 'done'
pending_mask = statuses == 'pending'
cancelled_mask = statuses == 'cancelled'

print('Суми:    ', amounts)
print('\nСтатуси: ', statuses)
print(f'\nСума всіх замовлень: {amounts[done_mask].sum()}$')
print(f'\nКількість \'pending\': {len(amounts[pending_mask])}')
# print(f'\nСередня сума скасованих: {amounts[cancelled_mask].mean()}')
print(f'\nСередня сума скасованих: {amounts[cancelled_mask].sum() / len(amounts[cancelled_mask])}')
print(f'\nЗавершені замовлення з сумою > 1000: {amounts[done_mask & (amounts > 1000)]}')

Суми:     [1060 3972 3292  666 4626 3644 3371 3119  330 1885  969 2591 2633 1384
 4755 3585 4317 3104  674 1282]

Статуси:  ['done' 'done' 'cancelled' 'done' 'done' 'pending' 'done' 'cancelled'
 'done' 'cancelled' 'pending' 'done' 'done' 'cancelled' 'done' 'done'
 'done' 'done' 'done' 'pending']

Сума всіх замовлень: 35684$

Кількість 'pending': 3

Середня сума скасованих: 2420.0

Завершені замовлення з сумою > 1000: [1060 3972 4626 3371 2591 2633 4755 3585 4317 3104]


### 📋 Задача 20+ (додаткова)
Є масив зарплат співробітників. Виконай:
1. Знайди тих, чия зарплата вище середньої
2. Знайди тих, чия зарплата нижче 30000 грн
3. Заміни всі зарплати нижче 25000 значенням 25000 (мінімальна ставка)
4. Виведи масив до і після зміни

In [ ]:
salaries = np.array([45000, 28000, 72000, 19000, 38000,
                     55000, 23000, 61000, 34000, 82000])
avg_sal = salaries.sum() / len(salaries)
low_sal = salaries < 30000

print(f'Зарплата вище середньої: {salaries[salaries > avg_sal]}')
print(f'Зарплата нижче 30000: {salaries[low_sal]}')
salaries[salaries < 25000] = 25000
print(f'Після заміни: {salaries}')

Зарплата вище середньої: [72000 55000 61000 82000]
Зарплата нижче 30000: [28000 19000 23000]
Після заміни: [45000 28000 72000 25000 38000 55000 25000 61000 34000 82000]


---
## Блок 2.5 — Агрегація по матрицях

### 📋 Задача 22
Є матриця продажів: 4 менеджери × 6 місяців. Знайди **без циклів**:
1. Загальні продажі кожного менеджера (сума по рядках, `axis=1`)
2. Загальні продажі кожного місяця (сума по стовпцях, `axis=0`)
3. Найкращий менеджер — `argmax()`
4. Найкращий місяць
5. Середнє по всій матриці

In [ ]:
sales = np.array([
    [45, 52, 48, 61, 55, 70],   # Менеджер 1
    [38, 44, 60, 55, 68, 72],   # Менеджер 2
    [62, 58, 51, 67, 73, 65],   # Менеджер 3
    [41, 49, 54, 47, 59, 63],   # Менеджер 4
])  # одиниці — тисячі грн

managers = ['Олена', 'Максим', 'Аня', 'Богдан']
months   = ['Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер']

best_mng_idx = sales.sum(axis=1).argmax()
best_month_idx = sales.sum(axis=0).argmax()

print(f'Загальні продажі кожного менеджера: {sales.sum(axis=1)}')
print(f'Загальні продажі кожного місяця: {sales.sum(axis=0)}')
print(f'Найкращий менеджер: {managers[best_mng_idx]}')
print(f'Найкращий місяць: {months[best_month_idx]}')
print(f'Середнє по всій матриці: {sales.mean().round(2)}')

Загальні продажі кожного менеджера: [331 337 376 313]
Загальні продажі кожного місяця: [186 203 213 230 255 270]
Найкращий менеджер: Аня
Найкращий місяць: Чер
Середнє по всій матриці: 56.54


### 📋 Задача 22+ (додаткова)
Є матриця оцінок: 3 студенти × 4 предмети. Знайди:
1. Середній бал кожного студента (по рядках)
2. Середній бал по кожному предмету (по стовпцях)
3. Максимальний бал у кожного студента
4. Студент з найвищим середнім балом

In [ ]:
grades = np.array([
    [85, 72, 91, 78],   # Студент 1
    [63, 88, 74, 95],   # Студент 2
    [90, 65, 82, 70],   # Студент 3
])

students = ['Олена', 'Максим', 'Аня']
subjects = ['Математика', 'Програмування', 'Статистика', 'Англійська']

max_grades = grades.max(axis=1)
best_student_idx = grades.mean(axis=1).argmax()

print(f'Середній бал кожного студента: {grades.sum(axis=1)}')
print(f'Середній бал по кожному предмету: {grades.sum(axis=0)}')
print(f'Максимальний бал у кожного студента: {dict(zip(students, max_grades.tolist()))}')
print(f'Студент з найвищим середнім балом: {students[best_student_idx]}')

Середній бал кожного студента: [326 320 307]
Середній бал по кожному предмету: [238 225 247 243]
Максимальний бал у кожного студента: {'Олена': 91, 'Максим': 95, 'Аня': 90}
Студент з найвищим середнім балом: Олена


---
## Блок 2.6 — Комплексні задачі

### 📋 Задача 23 — Нормалізація даних
Нормалізація (Min-Max scaling) — важлива техніка в ML.
Формула: `x_norm = (x - min) / (max - min)`
Результат завжди від 0 до 1.

Напиши функцію `normalize(arr)` і застосуй до масиву.

In [ ]:
def normalize(arr):
    return (arr - arr.min()) / (arr.max() - arr.min())

scores = np.array([45, 72, 88, 34, 91, 60, 77, 55, 83, 49])
normalized = normalize(scores)

print('Оригінал:    ', scores)
print('Нормалізовано:', normalized)
# Мін має бути 0, макс — 1


Оригінал:     [45 72 88 34 91 60 77 55 83 49]
Нормалізовано: [0.19298246 0.66666667 0.94736842 0.         1.         0.45614035
 0.75438596 0.36842105 0.85964912 0.26315789]


### 📋 Задача 24 — Виявлення викидів
Викид — значення далі ніж **2 стандартних відхилення** від середнього.

Умова викиду: `|x - mean| > 2 * std`

Знайди та виведи викиди та їх індекси.

In [ ]:
data = np.array([23, 25, 22, 24, 26, 150, 23, 25, 22, 24,
                 21, 27, 23, 25, -80, 24, 26, 23, 25, 22])

# 1. Порахуй mean та std
# 2. Знайди маску викидів — hint: np.abs()
# 3. Виведи самі викиди та їх індекси — hint: np.where()

avg = data.mean()
std = data.std()

mask = np.abs(data - avg) > 2 * std

print('Викиди: ',data[mask])
print(f'Індекси: {np.where(mask)[0]}')

Викиди:  [150 -80]
Індекси: [ 5 14]


### 📋 Задача 25 — Фінальна комплексна
Є дані про 5 магазинів за 12 місяців.

Знайди **без циклів**:
1. Загальну річну виручку кожного магазину
2. Кращий місяць для кожного магазину (`argmax` по рядках)
3. Кількість місяців де виручка магазину була вище його власного середнього
4. Відсоток таких місяців від загальної кількості

In [ ]:
np.random.seed(7)
revenue = np.random.randint(50, 200, size=(5, 12))
stores  = ['Магазин A', 'Магазин B', 'Магазин C', 'Магазин D', 'Магазин E']
months  = ['Січ','Лют','Бер','Кві','Тра','Чер','Лип','Сер','Вер','Жов','Лис','Гру']

print('Дані (тис. грн):')
print(revenue)

year_total = revenue.sum(axis=1)
best_month = revenue.argmax(axis=1)
avg_by_store = revenue.mean(axis=1)
above_avg = (revenue > avg_by_store.reshape(-1, 1)).sum(axis=1)
pct = (above_avg / revenue.shape[1] * 100).round(2)

print(f'\nЗагальна річна виручка кожного магазину: \n{dict(zip(stores, year_total.tolist()))}')
print(f'\nКращий місяць для кожного магазину: \n{dict(zip(stores, best_month.tolist()))}')
print(f'\nКількість місяців де виручка магазину була вище його власного середнього:\n{dict(zip(stores, above_avg.tolist()))}')
print(f'\nВідсоток таких місяців від загальної кількості:\n{dict(zip(stores, pct.tolist()))}')

Дані (тис. грн):
[[ 75 117 153 142 192  73 122 139 160  92 186 118]
 [177 185  50 125 105  56  69  94 119 106 162  84]
 [106  88  54 187 137 122 133  51 194 168 143 142]
 [121  73  60  85 111 185 142 199 150 117 173  69]
 [ 54  69  83 173  80 123 177 180 133 196  71 169]]

Загальна річна виручка кожного магазину: 
{'Магазин A': 1569, 'Магазин B': 1332, 'Магазин C': 1525, 'Магазин D': 1485, 'Магазин E': 1508}

Кращий місяць для кожного магазину: 
{'Магазин A': 4, 'Магазин B': 1, 'Магазин C': 8, 'Магазин D': 7, 'Магазин E': 9}

Кількість місяців де виручка магазину була вище його власного середнього:
{'Магазин A': 6, 'Магазин B': 5, 'Магазин C': 7, 'Магазин D': 5, 'Магазин E': 6}

Відсоток таких місяців від загальної кількості:
{'Магазин A': 50.0, 'Магазин B': 41.67, 'Магазин C': 58.33, 'Магазин D': 41.67, 'Магазин E': 50.0}


---
## 📋 Ключові прийоми аналітика

### Python — базовий синтаксис

```python
# ── Типи та конвертація ──────────────────────────────────
type(x)            # дізнатись тип змінної
int('42')          # рядок → ціле число
float('3.14')      # рядок → дійсне число
str(100)           # число → рядок
bool(0)            # будь-що → булеве

# ── Рядки ────────────────────────────────────────────────
s.strip()          # прибрати пробіли по краях
s.split(',')       # розбити на список по розділювачу
s.replace('a','b') # замінити підрядок
s.lower()          # всі малі літери
s.upper()          # всі великі літери
s.title()          # Перша Велика В Кожному Слові
s.startswith('К')  # чи починається з ...
f'{val:.2f}'       # форматування числа (2 знаки після коми)
f'{val:>8}'        # вирівняти праворуч на 8 символів

# ── Списки ───────────────────────────────────────────────
lst.append(x)      # додати в кінець
lst.remove(x)      # видалити перше входження x
lst.sort()         # сортувати на місці (змінює список)
sorted(lst)        # повернути новий відсортований список
lst[a:b]           # зріз від a до b (b не включається)
lst[::2]           # кожен другий елемент
lst[::-1]          # реверс списку
len(lst)           # кількість елементів

# List comprehension — одним рядком:
[x*2 for x in lst]              # застосувати до всіх
[x for x in lst if x > 0]       # відфільтрувати
[f'{x} грн' for x in lst]       # перетворити на рядки

# ── Словники ─────────────────────────────────────────────
d['key']           # отримати значення
d['key'] = val     # додати або оновити
d.keys()           # всі ключі
d.values()         # всі значення
d.items()          # пари (ключ, значення)
'key' in d         # чи є ключ у словнику

# ── Цикли та умови ───────────────────────────────────────
for i, val in enumerate(lst):   # індекс + значення
for a, b in zip(lst1, lst2):    # пари з двох списків
continue                         # перейти до наступної ітерації
break                            # вийти з циклу

# ── Функції ──────────────────────────────────────────────
min(lst), max(lst), sum(lst), len(lst)   # вбудовані агрегати
round(x, 2)                              # округлення
abs(x)                                   # модуль числа
```

---

### NumPy — масиви та операції

```python
import numpy as np

# ── Створення масивів ────────────────────────────────────
np.array([1, 2, 3])          # зі списку
np.zeros((3, 4))             # нулі розміром 3×4
np.ones((2, 5))              # одиниці розміром 2×5
np.full((3, 3), 7)           # заповнити числом 7
np.eye(4)                    # одинична матриця 4×4
np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)         # 5 рівних точок від 0 до 1
np.random.randint(1, 100, 10) # 10 випадкових цілих 1–99
np.random.randn(5)            # 5 чисел нормального розподілу

# ── Форма та інформація ──────────────────────────────────
arr.shape     # розміри: (рядки, стовпці)
arr.ndim      # кількість вимірів
arr.size      # загальна кількість елементів
arr.dtype     # тип даних (int64, float64...)
arr.reshape(3, 4)   # нова форма (кількість елементів та сама)
arr.flatten()       # розгорнути у 1D

# ── Індексація та зрізи ──────────────────────────────────
arr[0]          # перший елемент (1D)
arr[-1]         # останній
arr[2:5]        # елементи з індексу 2 по 4
arr[::2]        # кожен другий
arr[::-1]       # зворотній порядок

# Для 2D матриці:
m[0, :]         # весь перший рядок
m[:, 1]         # весь другий стовпець
m[1:3, 1:3]     # підматриця рядки 1–2, стовпці 1–2
m[-1, :]        # останній рядок
m[:, -1]        # останній стовпець

# ── Математичні операції (без циклів!) ───────────────────
arr * 2            # помножити всі елементи на 2
arr + 10           # додати до всіх
arr1 * arr2        # поелементне множення двох масивів
np.sqrt(arr)       # квадратний корінь
np.abs(arr)        # абсолютне значення
np.round(arr, 2)   # округлення

# ── Агрегатні функції ────────────────────────────────────
arr.sum()          # сума всіх
arr.mean()         # середнє
arr.std()          # стандартне відхилення
arr.min()          # мінімум
arr.max()          # максимум
np.median(arr)     # медіана

# Для матриць — по осях:
m.sum(axis=0)      # сума по стовпцях ↓ (результат — рядок)
m.sum(axis=1)      # сума по рядках → (результат — стовпець)
m.mean(axis=1, keepdims=True)  # зберегти форму для broadcast

# ── Знайти позицію ───────────────────────────────────────
np.argmin(arr)     # індекс мінімального елемента
np.argmax(arr)     # індекс максимального елемента
np.where(умова)    # індекси де умова True

# ── Булева індексація (фільтрація) ───────────────────────
arr[arr > 5]             # лише елементи > 5
arr[arr < 0] = 0         # замінити від'ємні нулем
mask = arr > 5
arr[mask]                # застосувати маску
arr[~mask]               # інвертована маска (НЕ)

# Кілька умов:
arr[(arr > 5) & (arr < 20)]   # І
arr[(arr < 0) | (arr > 100)]  # АБО

# ── Корисні прийоми ──────────────────────────────────────
mask.sum()               # кількість True (скільки відповідає умові)
mask.mean() * 100        # відсоток True

arr.copy()               # копія (зміни не вплинуть на оригінал)

# Нормалізація Min-Max:
(arr - arr.min()) / (arr.max() - arr.min())

# Виявлення викидів (правило 2σ):
np.abs(arr - arr.mean()) > 2 * arr.std()

# Z-score (стандартизація):
(arr - arr.mean()) / arr.std()
```